### ISSUE TITLE
JHOVE hangs with TIFF file "m1-fe50c06bcf744c640005967082a93ead" from Google Image Test Suite

### ISSUE THREAD

**Issue by friesey** [openpreserve/jhove#178]
## Dev Effort
1D

## Description
Dear Folks,
I currently run a test with the Google ImagetestSuite (https://code.google.com/archive/p/imagetestsuite/downloads/) and obviously at least one TIFF file cannot be processed.
The programm stopps in this code:
"JhoveBase.class" in line 588, 
   if (!processFile(app, module, false, file, info)) {
I copy you the full error I get in Eclipse (I run the JHOVE as a Java library, though the JHOVE Gui runs into the same problem, but there I do not have any error messages):
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at edu.harvard.hul.ois.jhove.module.tiff.IFD.readASCII(IFD.java:557)
	at edu.harvard.hul.ois.jhove.module.tiff.TiffIFD.lookupTag(TiffIFD.java:3156)
	at edu.harvard.hul.ois.jhove.module.tiff.IFD.parse(IFD.java:320)
	at edu.harvard.hul.ois.jhove.module.tiff.IFD.parse(IFD.java:218)
	at edu.harvard.hul.ois.jhove.module.TiffModule.parseIFDChain(TiffModule.java:1114)
	at edu.harvard.hul.ois.jhove.module.TiffModule.parseIFDs(TiffModule.java:1088)
	at edu.harvard.hul.ois.jhove.module.TiffModule.parseIFDs(TiffModule.java:1051)
	at edu.harvard.hul.ois.jhove.module.TiffModule.parse(TiffModule.java:449)
	at edu.harvard.hul.ois.jhove.JhoveBase.processFile(JhoveBase.java:803)
	at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:588)
I hope you can handle the problem. If I run into more files which cause the prpblem, I will add them to this issue.
Best regards, Yvonne

**Comment by friesey** [comment]
File "m5-299787ea764c0a88bc481364eded5556" throws a very similar error, here it is:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at edu.harvard.hul.ois.jhove.module.tiff.IFD.readShortArray(IFD.java:847)
	at edu.harvard.hul.ois.jhove.module.tiff.TiffIFD.lookupTag(TiffIFD.java:3215)
	at edu.harvard.hul.ois.jhove.module.tiff.IFD.parse(IFD.java:320)
	at edu.harvard.hul.ois.jhove.module.tiff.IFD.parse(IFD.java:218)
	at edu.harvard.hul.ois.jhove.module.TiffModule.parseIFDChain(TiffModule.java:1114)
	at edu.harvard.hul.ois.jhove.module.TiffModule.parseIFDs(TiffModule.java:1088)
	at edu.harvard.hul.ois.jhove.module.TiffModule.parseIFDs(TiffModule.java:1051)
	at edu.harvard.hul.ois.jhove.module.TiffModule.parse(TiffModule.java:449)
	at edu.harvard.hul.ois.jhove.JhoveBase.processFile(JhoveBase.java:803)
	at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:588)

**Comment by carlwilson** [comment]
Tested and no longer an issue with current version.
