### ISSUE TITLE
File causes "MalformedURLException"

### ISSUE THREAD

**Issue by friesey** [openpreserve/jhove#182]
## Dev Effort
1D

## Description
Dear Folks, 
File "m2-63c8b14ea08a18c884d05a3431716047" from the Google Image Testsuite causes the Exception:
"java.net.MalformedUrlException:unknown protocol: c"
java.net.MalformedURLException: unknown protocol: c
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at output.XmlParserJhove.parseXmlFile(XmlParserJhove.java:32)
Unfortunately, this causes the programm to stop and it won't examine the rest of the files in the folder.

Interestingly, this only happens wiht JHOVE as a library. The GUI does examine the file and has the following error messages:
ErrorMessage: Unknown data tyoe
ErrorMessage: Tag 2 out of sequence
ErrorMessage: Tag 0 out of sequence
ErrorMessage: IFD offset not word-aligned: 18977

Best, Yvonne

**Comment by friesey** [comment]
File "m2-d1d366d7965db766c19a66c7a2ccbb6b" causes the same error when examined with the JHOVE library and can be proceed via the JHOVE GUI. It gets the error message with the JHOVE GUI: 
ErrorMessage: Type mismatch for tag 273; expecting 3 or 4, saw 1

**Comment by carlwilson** [comment]
This is more likely to do with the library call as the application works fine. I suspect the Module or JHOVE app isn't set up right when the call's made.

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [File causes "MalformedURLException" #182 - Assigned to TBA](https://trello.com/c/oVYXM1pq/14-file-causes-malformedurlexception-182-assigned-to-tba)
