### ISSUE TITLE
Using Tiff-Hul module, unhandled excretion validating some files

### ISSUE THREAD

**Issue by jondgilbertP1** [openpreserve/jhove#431]
When analyzing files processed form Phase One Raw files (both in Capture One and ACR) validation experiences an unhandled exception.  If I disable camera metadata when processing to tiff, the file now passes.

Exif (verbose) of the Tif is attached.

**From terminal:**
Apr 03, 2019 8:39:20 AM edu.harvard.hul.ois.jhove.JhoveBase process
SEVERE: Validation ended prematurely due to an unhandled exception.
java.lang.IllegalArgumentException: Cannot format given Object as a Number
	at java.base/java.text.DecimalFormat.format(DecimalFormat.java:518)
	at java.base/java.text.Format.format(Format.java:158)
	at java.base/java.text.MessageFormat.subformat(MessageFormat.java:1344)
	at java.base/java.text.MessageFormat.format(MessageFormat.java:885)
	at java.base/java.text.Format.format(Format.java:158)
	at java.base/java.text.MessageFormat.format(MessageFormat.java:860)
	at edu.harvard.hul.ois.jhove.module.tiff.IFD.addIntegerProperty(IFD.java:417)
	at edu.harvard.hul.ois.jhove.module.tiff.ExifIFD.getProperty(ExifIFD.java:513)
	at edu.harvard.hul.ois.jhove.module.TiffModule.parse(TiffModule.java:556)
	at edu.harvard.hul.ois.jhove.JhoveBase.processFile(JhoveBase.java:775)
	at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:560)
	at edu.harvard.hul.ois.jhove.JhoveBase.dispatch(JhoveBase.java:432)
	at edu.harvard.hul.ois.jhove.viewer.JhoveWindow.openAndParse(JhoveWindow.java:618)
	at edu.harvard.hul.ois.jhove.viewer.JhoveWindow.pickAndAnalyzeFileList1(JhoveWindow.java:418)
	at edu.harvard.hul.ois.jhove.viewer.JhoveWindow$ParseThread.run(JhoveWindow.java:881)

**from Repinfo:**
JhoveView (Rel. 1.22.0-RC2, 2019-04-02)
 Date: 2019-04-03 08:38:57 PDT
 RepresentationInformation: /Users/JOG/Pictures/Cases/Output/C1-12-Atom-Target-600-Actual-595.tif
  ReportingModule: TIFF-hul, Rel. 1.8.0-RC2 (2019-03-29)
  LastModified: 2019-04-03 06:13:55 PDT
  Size: 79132232
  Format: TIFF
  Version: 6.0
  Status: Unknown
  SignatureMatches:
   TIFF-hul
  ErrorMessage: Validation ended prematurely due to an unhandled exception.
  MIMEtype: image/tiff
  Profile: Baseline RGB (Class R), DLF Benchmark for Faithful Digital Reproductions of Monographs and Serials: color

[Exif.txt](https://github.com/openpreserve/jhove/files/3039538/Exif.txt)

**Comment by carlwilson** [comment]
Hi @jondgilbertP1 would it be possible to send me an example file for this please, a generic example would be fine. It'll just make life a little easier when tracing the problem thanks.

**Comment by jondgilbertP1** [comment]
Certainly... sample raws available here: https://phaseone.sharefile.com/d-s79562cd3f9c4b13a

**Comment by tledoux** [comment]
The problem is related to #364 : the WhiteBalance provided is out of the scope of the Exif standard.
So an error message TIFF-HUL-66 is generated.

However, the message is defined, in ErrorMessages.properties, as
`TIFF-HUL-66= {0,number,#} value out of range: {1,number,#}`
but the first parameter given is not an Integer but a String.

So the correction to the unhandled exception should be to replace the error message by:
`TIFF-HUL-66= {0} value out of range: {1,number,#}`
then we go back too #364 which is a more functional issue.
