### ISSUE TITLE
Average JPEG displays text/audit results, throws error when handled as XML

### ISSUE THREAD

**Issue by ablwr** [openpreserve/jhove#459]
Using latest, version 1.22. Version 1.20 doesn't have this issue.

JHOVE will give me standard results, but if I seek to have the results handled in XML, I get an error.

Here is the stacktrace:
```
May 23, 2019 1:49:51 PM Jhove main
SEVERE: null
java.lang.NullPointerException
	at edu.harvard.hul.ois.jhove.handler.XmlHandler.rationalToString(XmlHandler.java:4464)
	at edu.harvard.hul.ois.jhove.handler.XmlHandler.showNisoImageCaptureMetadata20(XmlHandler.java:3606)
	at edu.harvard.hul.ois.jhove.handler.XmlHandler.showNisoImageMetadata20(XmlHandler.java:3094)
	at edu.harvard.hul.ois.jhove.handler.XmlHandler.showNisoImageMetadata(XmlHandler.java:1229)
	at edu.harvard.hul.ois.jhove.handler.XmlHandler.showProperty(XmlHandler.java:783)
	at edu.harvard.hul.ois.jhove.handler.XmlHandler.showProperty(XmlHandler.java:807)
	at edu.harvard.hul.ois.jhove.handler.XmlHandler.showProperty(XmlHandler.java:807)
	at edu.harvard.hul.ois.jhove.handler.XmlHandler.showProperty(XmlHandler.java:807)
	at edu.harvard.hul.ois.jhove.handler.XmlHandler.show(XmlHandler.java:466)
	at edu.harvard.hul.ois.jhove.RepInfo.show(RepInfo.java:598)
	at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:601)
	at edu.harvard.hul.ois.jhove.JhoveBase.dispatch(JhoveBase.java:432)
	at Jhove.main(Jhove.java:281)
```

Fairly standard .jpeg, here's the output from `file`: `JPEG image data, JFIF standard 1.02, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=12, manufacturer=Panasonic, model=DMC-FS20, orientation=upper-left, xresolution=178, yresolution=186, resolutionunit=2, software=Ver.1.0  , datetime=2011:07:30 17:09:30], baseline, precision 8, 800x600, frames 3` You can download it [here](https://github.com/artefactual/archivematica-sampledata/blob/master/TestTransfers/Evelyn's%20photos/objects/evelyn's%20photo.jpg) for testing.

**Comment by tledoux** [comment]
This is the same behavior that #502 : the PR #504 corrects the problem.

**Comment by ablwr** [comment]
I will close as this is a duplicate!
