### ISSUE TITLE
ReleaseDetailsTest.java fails when compiling during standard time (NZST)

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#48]
Likely because the time zone is explicitly set to daylight time here, as per, https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html#getDisplayName(boolean,%20int) when true is called: 

```
TimeZone.getDefault().getDisplayName(true, TimeZone.SHORT)
```

Affected code here: 

https://github.com/openpreserve/jhove/blob/1ca1f482e75575f76a3cd1eb9704605c9cab5045/jhove-core/src/test/java/org/openpreservation/jhove/ReleaseDetailsTest.java#L70

**Comment by carlwilson** [comment]
No time to do this on the Hack Day as coordinating and testing took priority, returning to the 1.16 fold.

**Comment by derDaywalker** [comment]
Hi,
if you solve this problem, please consider another annoying problem. I wanted to compile jhove on a german machine and received following error:

`org.junit.ComparisonFailure: expected:<...Sun Jul 31 00:00:00 [MESZ] 2011]> but was:<...Sun Jul 31 00:00:00 [CEST] 2011]>`

Notice: TimeZone.getDefault().getDisplayName(true, TimeZone.SHORT) returns MESZ, whereas the instance string returns CEST. So there is a mess up with locale dependent representation of the same timezone...

My dirty hack was to force default locale to US (on getDisplayName):
`assertEquals("ReleaseDetails [version=0.1.2-TESTER, buildDate=Sun Jul 31 00:00:00 " + TimeZone.getDefault().getDisplayName(true, TimeZone.SHORT, Locale.US) + " 2011]", instance.toString());`

Maybe there is a better solution?!? But I'm not an expert, therefore it would be great if you solve this bug :). 

Some details of my setup:
jhove git version: 'origin/release-1.14'
javac version 1.8.0_121
os: ubuntu 14.04
locale:
```
LANG=de_DE.UTF-8
LANGUAGE=de_DE
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```


Just in case you need the full error log:
```
-------------------------------------------------------------------------------
Test set: org.openpreservation.jhove.ReleaseDetailsTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.152 sec <<< FAILURE!
testToString(org.openpreservation.jhove.ReleaseDetailsTest)  Time elapsed: 0.01 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...Sun Jul 31 00:00:00 [MESZ] 2011]> but was:<...Sun Jul 31 00:00:00 [CEST] 2011]>
        at org.junit.Assert.assertEquals(Assert.java:123)
        at org.junit.Assert.assertEquals(Assert.java:145)
        at org.openpreservation.jhove.ReleaseDetailsTest.testToString(ReleaseDetailsTest.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
```
