### ISSUE TITLE
module class value in jhove.conf when running jhove in intellij

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#482]
I'm trying to learn more about the internal working of JHOVE and followed this guide about how to set up JHOVE running in a debugger:
https://www.dpoc.ac.uk/2018/08/09/jhove-running-in-a-debugger/ 
I ran into a problem setting the correct class values in the jhove.conf file. 
The original value, e.g.
 <module>
  <class>edu.harvard.hul.ois.jhove.module.PdfModule</class>
 </module>
result in an error:
# # # 
Cannot instantiate module: edu.harvard.hul.ois.jhove.module.PdfModule
edu.harvard.hul.ois.jhove.JhoveException: Cannot instantiate module: edu.harvard.hul.ois.jhove.module.PdfModule
	at edu.harvard.hul.ois.jhove.JhoveBase.init(JhoveBase.java:319)
	at Jhove.main(Jhove.java:240)
# # # 

Could anyone let me know what I need to set the module class value to to make it work?

**Comment by carlwilson** [comment]
Hi @asciim0,
I suspect that it's not the value but rather the fact that the class can't be found for some reason. To confirm, you're using the IntelliJ IDE? I'm an Eclipse user myself but I can try setting this up myself to see if I can replicate it. That won't be until next week though.

**Comment by asciim0** [comment]
Yup, I'm using IntelliJ IDEA Community Edition (2019.2.3). Thanks!

**Comment by samalloing** [comment]
Hi Michelle,

I get the same error on the command line if I use something like java -jar bin/jhove-apps-1.22.1.jar -c conf/jhove.conf. In version 1.20 this worked for me. Now you can use the jhove.bat script to make it work. For example for the Pdf it is jhove.bat -m PDF-hul

Sam

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [module class value in jhove.conf when running jhove in intellij #482 - Assigned to TBA](https://trello.com/c/tFSm7iEa/44-module-class-value-in-jhoveconf-when-running-jhove-in-intellij-482-assigned-to-tba)
