### ISSUE TITLE
java.lang.ClassCastException: edu.harvard.hul.ois.jhove.module.pdf.PdfSimpleObject cannot be cast to edu.harvard.hul.ois.jhove.module.pdf.PdfDictionary

### ISSUE THREAD

**Issue by bdc34** [openpreserve/jhove#50]
I'm getting a exception when running jhove on a PDF. This happens rarely. 

``````
jhove$ ./jhove -c ../cular/ingest/target/classes/jhove.conf ~/fulltext.pdf 
Sep 16, 2015 1:21:25 PM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level
java.lang.ClassCastException: edu.harvard.hul.ois.jhove.module.pdf.PdfSimpleObject cannot be cast to edu.harvard.hul.ois.jhove.module.pdf.PdfDictionary
at edu.harvard.hul.ois.jhove.module.PdfModule.readDocCatalogDict(Unknown Source)
at edu.harvard.hul.ois.jhove.module.PdfModule.parse(Unknown Source)
at edu.harvard.hul.ois.jhove.JhoveBase.processFile(Unknown Source)
at edu.harvard.hul.ois.jhove.JhoveBase.process(Unknown Source)
at edu.harvard.hul.ois.jhove.JhoveBase.dispatch(Unknown Source)
at Jhove.main(Unknown Source)
Jhove (Rel. 1.11, 2013-09-29)
Date: 2015-09-16 13:21:26 EDT
RepresentationInformation: /users/bdc34/fulltext.pdf
ReportingModule: BYTESTREAM, Rel. 1.3 (2007-04-10)
LastModified: 2015-09-16 13:08:10 EDT
Size: 938845
Format: bytestream
Status: Well-Formed and valid
SignatureMatches:
PDF-hul
MIMEtype: application/octet-stream```
``````

**Comment by bdc34** [comment]
Running it with -l ALL I get something like this:

```
...
Sep 17, 2015 11:36:37 AM edu.harvard.hul.ois.jhove.module.PdfModule readDocCatalogDict
WARNING: Tried to cat non-dictionary to PdfDictionary
java.lang.ClassCastException: edu.harvard.hul.ois.jhove.module.pdf.PdfSimpleObject cannot be cast to edu.harvard.hul.ois.jhove.module.pdf.PdfDictionary
...
```

**Comment by nclarkekb** [comment]
Including an offending PDF would most likely help someone when looking into this.

**Comment by bdc34** [comment]
Sorry. I'm no longer working on the project with access to that PDF.
