### ISSUE TITLE
JPEG-hul throws Null Pointer Exception when outputting XML

### ISSUE THREAD

**Issue by jackdos** [openpreserve/jhove#502]
I have some JPEG compressed EXIF files (fmt/645, x-fmt/390 and x-fmt/391) that cause the JPEG-hul (1.5.1) module to throw a null pointer exception when I attempt to convert the output to XML.

This error is not reproducable with JPEG-hul 1.4 and jhove 1.20.

The NPE stacktrace shows as:

```
Oct 21, 2019 12:05:53 PM Jhove main
SEVERE: null
java.lang.NullPointerException
        at edu.harvard.hul.ois.jhove.handler.XmlHandler.rationalToString(XmlHandler.java:4464)
        at edu.harvard.hul.ois.jhove.handler.XmlHandler.showNisoImageCaptureMetadata20(XmlHandler.java:3606)
        at edu.harvard.hul.ois.jhove.handler.XmlHandler.showNisoImageMetadata20(XmlHandler.java:3094)
        at edu.harvard.hul.ois.jhove.handler.XmlHandler.showNisoImageMetadata(XmlHandler.java:1229)
        at edu.harvard.hul.ois.jhove.handler.XmlHandler.showProperty(XmlHandler.java:783)
        at edu.harvard.hul.ois.jhove.handler.XmlHandler.showProperty(XmlHandler.java:807)
        at edu.harvard.hul.ois.jhove.handler.XmlHandler.showProperty(XmlHandler.java:807)
        at edu.harvard.hul.ois.jhove.handler.XmlHandler.showProperty(XmlHandler.java:807)
        at edu.harvard.hul.ois.jhove.handler.XmlHandler.show(XmlHandler.java:466)
        at edu.harvard.hul.ois.jhove.RepInfo.show(RepInfo.java:598)
        at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:601)
        at edu.harvard.hul.ois.jhove.JhoveBase.dispatch(JhoveBase.java:432)
        at Jhove.main(Jhove.java:281)
```

The full output in plain text is attached 
[properties.txt](https://github.com/openpreserve/jhove/files/3750321/properties.txt)

**Comment by carlwilson** [comment]
Thanks for this @jackdos, there'll be a testable fix for this later on this week.

**Comment by jackdos** [comment]
Thanks, I'll try and test it out as soon as I can
