### ISSUE TITLE
JHOVE 1.24.1 SecurityException

### ISSUE THREAD

**Issue by marhop** [openpreserve/jhove#564]
Hi,

Running a fresh install of JHOVE 1.24 (installed from current jhove-latest.jar) I get the following error:

```
Mar 13, 2020 10:55:27 AM Jhove main
SEVERE: Cannot instantiate module: edu.harvard.hul.ois.jhove.module.AsciiModule
edu.harvard.hul.ois.jhove.JhoveException: Cannot instantiate module: edu.harvard.hul.ois.jhove.module.AsciiModule
	at edu.harvard.hul.ois.jhove.JhoveBase.init(JhoveBase.java:346)
	at Jhove.main(Jhove.java:240)
Caused by: java.lang.SecurityException: class "edu.harvard.hul.ois.jhove.module.AsciiModule"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1150)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:905)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1014)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at edu.harvard.hul.ois.jhove.JhoveBase.init(JhoveBase.java:337)
	... 1 more
```

This does not happen with JHOVE 1.22 on the same system. I'm running Java 11 (OpenJDK) on a current Debian testing/bullseye. Output of `java -version`:

```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-2)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-2, mixed mode)
```

Any ideas?

Thanks,
Martin

**Comment by carlwilson** [comment]
Hi @marhop I have ideas and none of the potential causes reflects well on me ;) am looking now.

**Comment by carlwilson** [comment]
Thanks for reporting this @marhop. I fixed it on Monday and I believe that the release is fine now. It wasn't the code but a faulty JAR signing job, root cause human error.

**Comment by marhop** [comment]
Works like a charm now, thank you!

**Comment by carlwilson** [comment]
> Works like a charm now, thank you!

Good to know thanks.
