### ISSUE TITLE
NPE procesing jp2 file

### ISSUE THREAD

**Issue by pwinckles** [openpreserve/jhove#805]
Jhove 1.26.1 produces the following NPE when processing the attached jp2 file (note, I had to zip it because Github wasn't letting me upload jp2 files for whatever reason):

```
java.lang.NullPointerException: Cannot read the array length because "<local12>" is null
	at edu.harvard.hul.ois.jhove.module.Jpeg2000Module.calculateRatio(Jpeg2000Module.java:486)
	at edu.harvard.hul.ois.jhove.module.Jpeg2000Module.parse(Jpeg2000Module.java:424)
	at edu.harvard.hul.ois.jhove.JhoveBase.processFile(JhoveBase.java:813)
	at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:585)
```

The cause appears to be that `bitsPerSample` is null in [calculateRatio()](https://github.com/openpreserve/jhove/blob/e1f2a76e30af646799f729007419ecd8fa0dcf4c/jhove-modules/jpeg2000-hul/src/main/java/edu/harvard/hul/ois/jhove/module/Jpeg2000Module.java#L483). Tracing back from there, `bitsPerSample` is null because the [ImageHeaderBox](https://github.com/openpreserve/jhove/blob/integration/jhove-modules/jpeg2000-hul/src/main/java/edu/harvard/hul/ois/jhove/module/jpeg2000/ImageHeaderBox.java#L79) is deciding that the `bitsPerSample` field should be determined by the BPC Box, however the image does not have a BPC Box, so the value is never set.

It is unclear to me if it is correct to leave the value unset, in which case the `calculateRatio()` method needs updated to handle null values, or if the value should be being set by the ImageHeaderBox.

[image.zip](https://github.com/openpreserve/jhove/files/10213098/image.zip)

**Comment by carlwilson** [comment]
Hi @pwinckles, thanks for the feedback. We're currently working to put the next JHOVE release together. I'll take a look at the specs, and Jpylyzer's opinion. If there's an easy fix/obvious right way of doing this it will make 1.28. If there are questions I'll post here and it will be the subsequent release.

**Comment by carlwilson** [comment]
I've managed to reproduce this. I've also ran it through Jpylyzer which is more authoritative than JHOVE. It was also less than impressed:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<jpylyzer xmlns="http://openpreservation.org/ns/jpylyzer/v2/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://openpreservation.org/ns/jpylyzer/v2/ http://jpylyzer.openpreservation.org/jpylyzer-v-2-1.xsd">
<toolInfo>
    <toolName>jpylyzer</toolName>
    <toolVersion>2.1.0</toolVersion>
</toolInfo>
<file>
    <fileInfo>
        <fileName>28488272.jp2</fileName>
        <filePath>/home/cfw/Projects/opf/jhove/28488272.jp2</filePath>
        <fileSizeInBytes>21279816</fileSizeInBytes>
        <fileLastModified>2022-12-12T23:48:32</fileLastModified>
    </fileInfo>
    <statusInfo>
        <success>False</success>
        <failureMessage>unknown error, please report to developers by creating an issue at https://github.com/openpreserve/jpylyzer/issues</failureMessage>
    </statusInfo>
    <isValid format="jp2">False</isValid>
    <tests/>
    <properties/>
</file>
</jpylyzer>
```

Not sure either app is covering itself in glory here. It's not going to make this release now, I'm looking to get that out tomorrow while I play catch up after illness. I will take a closer look over the next couple of months, once this is done.

**Comment by bitsgalore** [comment]
FWIW I just came across this by chance, and this is now fixed in Jpylyzer. The fixed development version now correctly handles the missing Bits per Component Box, resulting in the following output:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<jpylyzer xmlns="http://openpreservation.org/ns/jpylyzer/v2/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://openpreservation.org/ns/jpylyzer/v2/ http://jpylyzer.openpreservation.org/jpylyzer-v-2-2.xsd">
<toolInfo>
    <toolName>cli.py</toolName>
    <toolVersion>2.2.0</toolVersion>
</toolInfo>
<file>
    <fileInfo>
        <fileName>28488272.jp2</fileName>
        <filePath>/home/johan/test/28488272.jp2</filePath>
        <fileSizeInBytes>21279816</fileSizeInBytes>
        <fileLastModified>2022-12-13T00:48:32</fileLastModified>
    </fileInfo>
    <statusInfo>
        <success>True</success>
    </statusInfo>
    <isValid format="jp2">False</isValid>
    <tests>
        <jp2HeaderBox>
            <containsBitsPerComponentBox>False</containsBitsPerComponentBox>
        </jp2HeaderBox>
        <bPCSignConsistentWithSIZ>False</bPCSignConsistentWithSIZ>
        <bPCDepthConsistentWithSIZ>False</bPCDepthConsistentWithSIZ>
    </tests>
    <properties>
      ::  ::
    </properties>
    <warnings/>
</file>
</jpylyzer>
```
