### ISSUE TITLE
 Java Error on Jhove CLI by json formatter class java.lang.Double cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by orgabor** [openpreserve/jhove#890]
If I run the cli with the -h option, the json output runs on the following error message.

SEVERE: class java.lang.Double cannot be cast to class java.lang.String (java.lang.Double and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.String (java.lang.Double and java.lang.String are in module java.base of loader 'bootstrap')
at edu.harvard.hul.ois.jhove.handler.JsonHandler.showScalarProperty(JsonHandler.java:726)
at edu.harvard.hul.ois.jhove.handler.JsonHandler.showProperty(JsonHandler.java:658)
at edu.harvard.hul.ois.jhove.handler.JsonHandler.showListProperty(JsonHandler.java:790)
at edu.harvard.hul.ois.jhove.handler.JsonHandler.showProperty(JsonHandler.java:662)
at edu.harvard.hul.ois.jhove.handler.JsonHandler.showListProperty(JsonHandler.java:790)
at edu.harvard.hul.ois.jhove.handler.JsonHandler.showProperty(JsonHandler.java:662)
at edu.harvard.hul.ois.jhove.handler.JsonHandler.show(JsonHandler.java:439)
at edu.harvard.hul.ois.jhove.RepInfo.show(RepInfo.java:563)
at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:649)
at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:576)
at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:576)
at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:576)
at edu.harvard.hul.ois.jhove.JhoveBase.process(JhoveBase.java:576)
at edu.harvard.hul.ois.jhove.JhoveBase.dispatch(JhoveBase.java:479)
at edu.harvard.hul.ois.jhove.Jhove.main(Jhove.java:265)

XML output works, but looks a bit damaged:

 <values arity="Scalar" type="String">
           <value>&lt;x:xmpmeta xmlns:x="adobe:ns:meta/"&gt;
  &lt;rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"&gt;
    &lt;rdf:Description xmlns:pdfaid="http://www.aiim.org/pdfa/ns/id/" rdf:about=""&gt;
      &lt;pdfaid:part&gt;3&lt;/pdfaid:part&gt;
      &lt;pdfaid:conformance&gt;B&lt;/pdfaid:conformance&gt;
    &lt;/rdf:Description&gt;
    &lt;rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" rdf:about=""&gt;
      &lt;dc:title&gt;
        &lt;rdf:Alt&gt;
          &lt;rdf:li lang="x-default"/&gt;
        &lt;/rdf:Alt&gt;
      &lt;/dc:title&gt;
    &lt;/rdf:Description&gt;
    &lt;rdf:Description xmlns:xmp="http://ns.adobe.com/xap/1.0/" rdf:about=""&gt;
      &lt;xmp:CreatorTool&gt;Konik Library&lt;/xmp:CreatorTool&gt;
      &lt;xmp:CreateDate&gt;2021-11-12T10:11:11+01:00&lt;/xmp:CreateDate&gt;
    &lt;/rdf:Description&gt;
    &lt;rdf:Description xmlns:pdf="http://ns.adobe.com/pdf/1.3/" rdf:about=""&gt;
      &lt;pdf:Producer&gt;Konik Library&lt;/pdf:Producer&gt;
    &lt;/rdf:Description&gt;
  &lt;/rdf:RDF&gt;
&lt;/x:xmpmeta&gt;</value>

**Comment by mutanthumb** [comment]
I have 151 files like this, if you need any for testing. FYI, spot checking showed that both the header version and the catalog base version were the same (1.7). I'm running Jhove (Rel. 1.34.0, 2025-07-02). I re-ran Jhove with text output, happy to share the files as well as the output reports.
